Repository Team-Wander/Wandering-Front, pull requests merged in 2024-11, with the labels that each got.

#19 🔀 postPage 퍼블리싱
  public/index.html
  src/App.tsx
  src/components/MateList/MateItem/index.tsx
  src/components/MateList/index.tsx
  src/components/Modal/Declaration/index.tsx
  src/components/Portal/index.tsx
  src/components/Portal/style.ts
  src/components/Post/DetailPost/PostHeader/index.tsx
  src/components/Post/DetailPost/PostHeader/style.ts
  src/components/Post/DetailPost/PostProfile/index.tsx
  src/components/Post/DetailPost/PostProfile/style.ts
  src/components/Post/DetailPost/index.tsx
  src/components/Post/DetailPost/style.ts
  src/components/Post/PostCard/style.ts
  src/components/Post/index.ts
  src/components/index.ts
  src/pages/post/index.tsx
  src/pages/post/style.ts
  src/style/emotion.d.ts
  src/style/theme.ts
  src/svg/LeftArrow.tsx
  src/svg/ReportIcon.tsx
  src/svg/index.ts
Labels: ✨ Feature, 🎨 Publishing

#18 🔀주소 검색 기능 구현
  src/components/AdressSearch/index.tsx
  src/components/AdressSearch/style.ts
  src/components/Input/index.tsx
  src/pages/write/index.tsx
  src/types/input.ts
Labels: ✨ Feature

#20 🔀 메인 페이지 및 헤더 수정
  src/components/Header/SearchList/index.tsx
  src/components/Header/SearchList/style.ts
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/components/Post/PostCard/style.ts
  src/pages/home/index.tsx
  src/pages/home/style.ts
Labels: ✨ Feature

#21 🔀참조 정리
  package-lock.json
  src/components/AddressSearch/index.tsx
  src/components/AddressSearch/style.ts
  src/components/Filter/Filter/index.tsx
  src/components/Filter/Filter/style.ts
  src/components/Filter/index.ts
  src/components/MateList/index.tsx
  src/components/Modal/ApproveAppointment/index.tsx
  src/components/Post/PostCard/TagList/index.tsx
  src/components/Post/PostCard/index.tsx
  src/components/Post/PostList/index.tsx
  src/components/index.ts
  src/pages/InputPage/index.tsx
  src/pages/home/index.tsx
  src/pages/temp/index.tsx
  src/pages/write/index.tsx
  src/style/emotion.d.ts
  src/svg/index.ts
  src/types/Card.ts
  src/types/input.ts
  yarn.lock
Labels: ⚙ Setting
