Repository Team-Wander/Wandering-Front, pull requests merged in 2024-09, with the labels that each got.

#4 🔀input component 추가
  .eslintrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/components/Input/index.tsx
  src/components/Input/style.ts
  src/pages/InputPage/index.tsx
  src/pages/InputPage/style.ts
  src/svg/SearchIcon.tsx
  src/types/index.ts
  src/types/input.ts
  yarn.lock
Labels: ✨ Feature

#5 🔀postCard 추가
  src/App.tsx
  src/components/Post/PostCard/MateList/MateItem/index.tsx
  src/components/Post/PostCard/MateList/MateItem/style.ts
  src/components/Post/PostCard/MateList/index.tsx
  src/components/Post/PostCard/MateList/style.ts
  src/components/Post/PostCard/TagList/TagItem/index.tsx
  src/components/Post/PostCard/TagList/TagItem/style.ts
  src/components/Post/PostCard/TagList/index.tsx
  src/components/Post/PostCard/TagList/style.ts
  src/components/Post/PostCard/index.tsx
  src/components/Post/PostCard/style.ts
  src/components/Post/index.ts
  src/components/index.ts
  src/components/index.tsx
  src/pages/Card/index.tsx
  src/pages/home/index.tsx
  src/pages/index.ts
  src/types/Card.ts
  yarn.lock
Labels: 🎨 Publishing

#6 🔀패키지 추가
  package-lock.json
  package.json
  yarn.lock
Labels: 🐞 Bug, ⚙ Setting

#8 🔀메인페이지 퍼블리싱
  .eslintrc.json
  package.json
  src/App.tsx
  src/components/Banner/index.tsx
  src/components/Banner/style.ts
  src/components/Filter/ChoiceList/ChoiceButton/index.tsx
  src/components/Filter/ChoiceList/ChoiceButton/style.ts
  src/components/Filter/ChoiceList/index.tsx
  src/components/Filter/ChoiceList/style.ts
  src/components/Filter/index.tsx
  src/components/Filter/style.ts
  src/components/Location/index.tsx
  src/components/Location/style.ts
  src/components/Modal/DeclarationModal/style.ts
  src/components/Modal/index.tsx
  src/components/Post/PostCard/MateList/MateItem/index.tsx
  src/components/Post/PostCard/MateList/MateItem/style.ts
  src/components/Post/PostCard/MateList/index.tsx
  src/components/Post/PostCard/TagList/TagItem/index.tsx
  src/components/Post/PostCard/TagList/TagItem/style.ts
  src/components/Post/PostCard/TagList/style.ts
  src/components/Post/PostCard/index.tsx
  src/components/Post/PostCard/style.ts
  src/components/Post/PostList/index.tsx
  src/components/Post/PostList/style.ts
  src/components/Post/index.ts
  src/components/index.ts
  src/pages/Card/index.tsx
  src/pages/home/index.tsx
  src/pages/home/style.ts
  src/pages/index.ts
  src/svg/BannerText.tsx
  src/svg/FilterIcon.tsx
  src/svg/PinIcon.tsx
  src/svg/SelectButton.tsx
  src/svg/XIcon.tsx
  src/svg/index.ts
  src/types/Card.ts
  src/types/report.ts
Labels: 🎨 Publishing
